-- Aidoku database schema — Postgres.
--
-- This is the actual DDL, applied automatically to the local dev Postgres
-- container on first startup (see docker-compose.yml's initdb mount).
-- AIDOKU_DESIGN.md §4 keeps a "rough sketch" version of this for reading
-- alongside the design rationale — this file is the source of truth for
-- the real schema.
--
-- No migration tool wired up yet (golang-migrate, goose, atlas, etc. are
-- all reasonable choices) — a single schema file is enough while there's
-- no backend or storage-layer code consuming it yet. Revisit once that
-- exists and the schema needs versioned, incremental changes.

-- Book: one row per ingested book. Reading level is assigned manually,
-- never derived by the pipeline — see pipeline/internal/catalog and
-- AIDOKU_DESIGN.md §7e. gutenberg_id is the pipeline's stable identifier
-- for a book (catalog.Entry.GutenbergID) — unique so re-running the
-- pipeline against the same book doesn't create a duplicate.
CREATE TABLE book (
    id           SERIAL PRIMARY KEY,
    gutenberg_id INTEGER NOT NULL UNIQUE,
    title        TEXT NOT NULL,
    author       TEXT NOT NULL,
    source_url   TEXT NOT NULL,
    level        SMALLINT NOT NULL CHECK (level BETWEEN 1 AND 10),
    language     TEXT NOT NULL DEFAULT 'en',
    status       TEXT NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'published')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Chunk: one reading chunk within a book, in reading order. "index" is
-- the chunk's position within its book (matches types.Chunk.Index from
-- Stage B's output) — the (book_id, index) pair is how the pipeline
-- addresses a chunk, so it's the unique key, not just a convenience.
CREATE TABLE chunk (
    id         SERIAL PRIMARY KEY,
    book_id    INTEGER NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    index      INTEGER NOT NULL,
    text       TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    UNIQUE (book_id, index)
);

-- Question: exactly one vocab, one grammar, one comprehension question
-- per chunk (enforced by the UNIQUE(chunk_id, type) below — a second
-- question of the same type for the same chunk is a schema violation,
-- not just an application bug). "highlight" is null for comprehension
-- questions (they're about the whole chunk, not one span) and required
-- for vocab/grammar — see question.ValidateQuestionSet in the pipeline,
-- which enforces the same rule before a row ever gets here.
CREATE TABLE question (
    id           SERIAL PRIMARY KEY,
    chunk_id     INTEGER NOT NULL REFERENCES chunk(id) ON DELETE CASCADE,
    type         TEXT NOT NULL CHECK (type IN ('vocab', 'grammar', 'comprehension')),
    prompt       TEXT NOT NULL,
    options      TEXT[] NOT NULL CHECK (array_length(options, 1) = 4),
    answer_index SMALLINT NOT NULL CHECK (answer_index BETWEEN 0 AND 3),
    explanation  TEXT NOT NULL,
    highlight    TEXT,
    UNIQUE (chunk_id, type),
    CHECK ((type = 'comprehension') = (highlight IS NULL))
);

-- Breakdown: the full post-answer explanation for a chunk. One-to-one
-- with chunk (not yet generated by the pipeline — see AIDOKU_DESIGN.md
-- §3 stage 4.3, "not built").
CREATE TABLE breakdown (
    id       SERIAL PRIMARY KEY,
    chunk_id INTEGER NOT NULL UNIQUE REFERENCES chunk(id) ON DELETE CASCADE,
    content  TEXT NOT NULL
);

-- UserProgress: intentionally minimal/provisional — gamification is
-- still "TBD in detail" (AIDOKU_DESIGN.md §5), and there's no users
-- table yet (no auth designed). Revisit this table's shape once that
-- design happens; user_id is left as a bare integer rather than a real
-- foreign key for now.
CREATE TABLE user_progress (
    user_id             INTEGER NOT NULL,
    book_id             INTEGER NOT NULL REFERENCES book(id) ON DELETE CASCADE,
    current_chunk_index INTEGER NOT NULL DEFAULT 0,
    streak_days         INTEGER NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, book_id)
);
